INSERT INTO `dict_countries` (`id`, `country`, `code`, `created_at`, `updated_at`) VALUES
	(1, 'Afganistan', 'AF', NOW(), NOW()),
	(2, 'Albania', 'AL', NOW(), NOW()),
	(3, 'Algieria', 'DZ', NOW(), NOW()),
	(4, 'Samoa Amerykańskie', 'AS', NOW(), NOW()),
	(5, 'Andora', 'AD', NOW(), NOW()),
	(6, 'Angola', 'AO', NOW(), NOW()),
	(7, 'Anguilla', 'AI', NOW(), NOW()),
	(8, 'Antarktyka', 'AQ', NOW(), NOW()),
	(9, 'Antigua i Barbuda', 'AG', NOW(), NOW()),
	(10, 'Argentyna', 'AR', NOW(), NOW()),
	(11, 'Armenia', 'AM', NOW(), NOW()),
	(12, 'Aruba', 'AW', NOW(), NOW()),
	(13, 'Australia', 'AU', NOW(), NOW()),
	(14, 'Austria', 'AT', NOW(), NOW()),
	(15, 'Azerbejdżan', 'AZ', NOW(), NOW()),
	(16, 'Bahamy', 'BS', NOW(), NOW()),
	(17, 'Bahrain', 'BH', NOW(), NOW()),
	(18, 'Bangladesz', 'BD', NOW(), NOW()),
	(19, 'Barbados', 'BB', NOW(), NOW()),
	(20, 'Białoruś', 'BY', NOW(), NOW()),
	(21, 'Belgia', 'BE', NOW(), NOW()),
	(22, 'Belize', 'BZ', NOW(), NOW()),
	(23, 'Benin', 'BJ', NOW(), NOW()),
	(24, 'Bermudy', 'BM', NOW(), NOW()),
	(25, 'Bhutan', 'BT', NOW(), NOW()),
	(26, 'Boliwia', 'BO', NOW(), NOW()),
	(27, 'Bonia i Hercegowina', 'BA', NOW(), NOW()),
	(28, 'Botswana', 'BW', NOW(), NOW()),
	(29, 'Wyspa Bouveta', 'BV', NOW(), NOW()),
	(30, 'Brazylia', 'BR', NOW(), NOW()),
	(31, 'Brytyjskie Terytorium Oceanu Indyjskiego', 'IO', NOW(), NOW()),
	(32, 'Brunei', 'BN', NOW(), NOW()),
	(33, 'Bułgaria', 'BG', NOW(), NOW()),
	(34, 'Burkina Faso', 'BF', NOW(), NOW()),
	(35, 'Burundi', 'BI', NOW(), NOW()),
	(36, 'Kambodża', 'KH', NOW(), NOW()),
	(37, 'Kamerun', 'CM', NOW(), NOW()),
	(38, 'Kanada', 'CA', NOW(), NOW()),
	(39, 'Republika Zielonego Przylšdka', 'CV', NOW(), NOW()),
	(40, 'Kajmany', 'KY', NOW(), NOW()),
	(41, 'Republika rodkowoafrykańska', 'CF', NOW(), NOW()),
	(42, 'Czad', 'TD', NOW(), NOW()),
	(43, 'Chile', 'CL', NOW(), NOW()),
	(44, 'Chiny', 'CN', NOW(), NOW()),
	(45, 'Wyspa Bożego Narodzenia', 'CX', NOW(), NOW()),
	(46, 'Wyspy Cocos', 'CC', NOW(), NOW()),
	(47, 'Kolumbia', 'CO', NOW(), NOW()),
	(48, 'Komory', 'KM', NOW(), NOW()),
	(49, 'Kongo', 'CG', NOW(), NOW()),
	(50, 'Demokratyczna Republika Konga', 'CD', NOW(), NOW()),
	(51, 'Wyspy Cooka', 'CK', NOW(), NOW()),
	(52, 'Kostaryka', 'CR', NOW(), NOW()),
	(53, 'Wybrzeże Koci Słoniowej', 'CI', NOW(), NOW()),
	(54, 'Chorwacja', 'HR', NOW(), NOW()),
	(55, 'Kuba', 'CU', NOW(), NOW()),
	(56, 'Cypr', 'CY', NOW(), NOW()),
	(57, 'Czechy', 'CZ', NOW(), NOW()),
	(58, 'Dania', 'DK', NOW(), NOW()),
	(59, 'Dżibutu', 'DJ', NOW(), NOW()),
	(60, 'Dominika', 'DM', NOW(), NOW()),
	(61, 'Dominikana', 'DO', NOW(), NOW()),
	(62, 'Ekwador', 'EC', NOW(), NOW()),
	(63, 'Egipt', 'EG', NOW(), NOW()),
	(64, 'Salwador', 'SV', NOW(), NOW()),
	(65, 'Gwinea Równikowa', 'GQ', NOW(), NOW()),
	(66, 'Erytrea', 'ER', NOW(), NOW()),
	(67, 'Estonia', 'EE', NOW(), NOW()),
	(68, 'Etiopia', 'ET', NOW(), NOW()),
	(69, 'Falklandy Malwiny', 'FK', NOW(), NOW()),
	(70, 'Wyspy Faraona', 'FO', NOW(), NOW()),
	(71, 'Fidżi', 'FJ', NOW(), NOW()),
	(72, 'Finlandia (ale nie do picia)', 'FI', NOW(), NOW()),
	(73, 'Francja', 'FR', NOW(), NOW()),
	(74, 'Gujana Francuska', 'GF', NOW(), NOW()),
	(75, 'Polinezja Francuska', 'PF', NOW(), NOW()),
	(76, 'Francuskie Terytoria Południowe', 'TF', NOW(), NOW()),
	(77, 'Gabon', 'GA', NOW(), NOW()),
	(78, 'Gambia', 'GM', NOW(), NOW()),
	(79, 'Georgia Południowa', 'GE', NOW(), NOW()),
	(80, 'Niemcy', 'DE', NOW(), NOW()),
	(81, 'Ghana', 'GH', NOW(), NOW()),
	(82, 'Gibraltar', 'GI', NOW(), NOW()),
	(83, 'Grecja', 'GR', NOW(), NOW()),
	(84, 'Grenlandia', 'GL', NOW(), NOW()),
	(85, 'Grenada', 'GD', NOW(), NOW()),
	(86, 'Gwadelupa', 'GP', NOW(), NOW()),
	(87, 'Guam', 'GU', NOW(), NOW()),
	(88, 'Gwatemala', 'GT', NOW(), NOW()),
	(89, 'Gwinea', 'GN', NOW(), NOW()),
	(90, 'Gwinea Bissau', 'GW', NOW(), NOW()),
	(91, 'Gujana', 'GY', NOW(), NOW()),
	(92, 'Haiti', 'HT', NOW(), NOW()),
	(93, 'Wyspy Heard i McDonalda', 'HM', NOW(), NOW()),
	(94, 'Watykan', 'VA', NOW(), NOW()),
	(95, 'Honduras', 'HN', NOW(), NOW()),
	(96, 'Hong Kong', 'HK', NOW(), NOW()),
	(97, 'Węgry', 'HU', NOW(), NOW()),
	(98, 'Islandia', 'IS', NOW(), NOW()),
	(99, 'Indie', 'IN', NOW(), NOW()),
	(100, 'Indonezja', 'ID', NOW(), NOW()),
	(101, 'Iran', 'IR', NOW(), NOW()),
	(102, 'Irak', 'IQ', NOW(), NOW()),
	(103, 'Irlandia', 'IE', NOW(), NOW()),
	(104, 'Izrael', 'IL', NOW(), NOW()),
	(105, 'Włochy', 'IT', NOW(), NOW()),
	(106, 'Jamaika', 'JM', NOW(), NOW()),
	(107, 'Japonia', 'JP', NOW(), NOW()),
	(108, 'Jordania', 'JO', NOW(), NOW()),
	(109, 'Kazachstan', 'KZ', NOW(), NOW()),
	(110, 'Kenia', 'KE', NOW(), NOW()),
	(111, 'Kiribati', 'KI', NOW(), NOW()),
	(112, 'Korea Północna', 'KP', NOW(), NOW()),
	(113, 'Korea Południowa', 'KR', NOW(), NOW()),
	(114, 'Kuwejt', 'KW', NOW(), NOW()),
	(115, 'Kirgistan', 'KG', NOW(), NOW()),
	(116, 'Laos', 'LA', NOW(), NOW()),
	(117, 'Łotwa', 'LV', NOW(), NOW()),
	(118, 'Liban', 'LB', NOW(), NOW()),
	(119, 'Lesotho', 'LS', NOW(), NOW()),
	(120, 'Liberia', 'LR', NOW(), NOW()),
	(121, 'Libia', 'LY', NOW(), NOW()),
	(122, 'Liechtenstein', 'LI', NOW(), NOW()),
	(123, 'Litwa', 'LT', NOW(), NOW()),
	(124, 'Luksemburg', 'LU', NOW(), NOW()),
	(125, 'Makau', 'MO', NOW(), NOW()),
	(126, 'Macedonia', 'MK', NOW(), NOW()),
	(127, 'Madagaskar', 'MG', NOW(), NOW()),
	(128, 'Malawi', 'MW', NOW(), NOW()),
	(129, 'Malezja', 'MY', NOW(), NOW()),
	(130, 'Malediwy', 'MV', NOW(), NOW()),
	(131, 'Mali', 'ML', NOW(), NOW()),
	(132, 'Malta', 'MT', NOW(), NOW()),
	(133, 'Wyspy Marshalla', 'MH', NOW(), NOW()),
	(134, 'Martynika', 'MQ', NOW(), NOW()),
	(135, 'Mauretania', 'MR', NOW(), NOW()),
	(136, 'Mauritius', 'MU', NOW(), NOW()),
	(137, 'Majotta', 'YT', NOW(), NOW()),
	(138, 'Meksyk', 'MX', NOW(), NOW()),
	(139, 'Mikronezja', 'FM', NOW(), NOW()),
	(140, 'Mołdawia', 'MD', NOW(), NOW()),
	(141, 'Monako', 'MC', NOW(), NOW()),
	(142, 'Mongolia', 'MN', NOW(), NOW()),
	(143, 'Montserrat', 'MS', NOW(), NOW()),
	(144, 'Maroko', 'MA', NOW(), NOW()),
	(145, 'Mozambik', 'MZ', NOW(), NOW()),
	(146, 'Birma', 'MM', NOW(), NOW()),
	(147, 'Namibia', 'NA', NOW(), NOW()),
	(148, 'Nauru', 'NR', NOW(), NOW()),
	(149, 'Nepal', 'NP', NOW(), NOW()),
	(150, 'Holandia', 'NL', NOW(), NOW()),
	(151, 'Antyle Holenderskie', 'AN', NOW(), NOW()),
	(152, 'Nowa Kaledonia', 'NC', NOW(), NOW()),
	(153, 'Nowa Zelandia', 'NZ', NOW(), NOW()),
	(154, 'Nikaragua', 'NI', NOW(), NOW()),
	(155, 'Niger', 'NE', NOW(), NOW()),
	(156, 'Nigeria', 'NG', NOW(), NOW()),
	(157, 'Niue', 'NU', NOW(), NOW()),
	(158, 'Norfolk', 'NF', NOW(), NOW()),
	(159, 'Mariany Północne', 'MP', NOW(), NOW()),
	(160, 'Norwegia', 'NO', NOW(), NOW()),
	(161, 'Oman', 'OM', NOW(), NOW()),
	(162, 'Pakistan', 'PK', NOW(), NOW()),
	(163, 'Palau', 'PW', NOW(), NOW()),
	(164, 'Palestyna', 'PS', NOW(), NOW()),
	(165, 'Panama', 'PA', NOW(), NOW()),
	(166, 'Papua-Nowa Gwinea', 'PG', NOW(), NOW()),
	(167, 'Paragwaj', 'PY', NOW(), NOW()),
	(168, 'Peru', 'PE', NOW(), NOW()),
	(169, 'Filipiny', 'PH', NOW(), NOW()),
	(170, 'Pitcairn', 'PN', NOW(), NOW()),
	(171, 'Polska', 'PL', NOW(), NOW()),
	(172, 'Portugalia', 'PT', NOW(), NOW()),
	(173, 'Portoryko', 'PR', NOW(), NOW()),
	(174, 'Katar', 'QA', NOW(), NOW()),
	(175, 'Reunion', 'RE', NOW(), NOW()),
	(176, 'Rumunia', 'RO', NOW(), NOW()),
	(177, 'Rosja', 'RU', NOW(), NOW()),
	(178, 'Rwanda', 'RW', NOW(), NOW()),
	(179, 'więta Helena i Zależne', 'SH', NOW(), NOW()),
	(180, 'Saint Kitts i Nevis', 'KN', NOW(), NOW()),
	(181, 'Saint Lucia', 'LC', NOW(), NOW()),
	(182, 'Saint Pierre i Miquelon', 'PM', NOW(), NOW()),
	(183, 'Saint Vincent i Grenadyny', 'VC', NOW(), NOW()),
	(184, 'Samoa', 'WS', NOW(), NOW()),
	(185, 'San Marino', 'SM', NOW(), NOW()),
	(186, 'Wyspy więtego Tomasza i Ksišżęca', 'ST', NOW(), NOW()),
	(187, 'Arabia Saudyjska', 'SA', NOW(), NOW()),
	(188, 'Senegal', 'SN', NOW(), NOW()),
	(189, 'Czarnogóra', 'ME', NOW(), NOW()),
	(190, 'Serbia', 'RS', NOW(), NOW()),
	(191, 'Seszele', 'SC', NOW(), NOW()),
	(192, 'Sierra Leone', 'SL', NOW(), NOW()),
	(193, 'Singapure', 'SG', NOW(), NOW()),
	(194, 'Słowacja', 'SK', NOW(), NOW()),
	(195, 'Słowenia', 'SI', NOW(), NOW()),
	(196, 'Wyspy Salomona', 'SB', NOW(), NOW()),
	(197, 'Somalia', 'SO', NOW(), NOW()),
	(198, 'Republika Południowej Afryki', 'ZA', NOW(), NOW()),
	(199, 'Georgia Południowa i Sandwich Południowy', 'GS', NOW(), NOW()),
	(200, 'Hiszpania', 'ES', NOW(), NOW()),
	(201, 'Sri Lanka', 'LK', NOW(), NOW()),
	(202, 'Sudan', 'SD', NOW(), NOW()),
	(203, 'Surinam', 'SR', NOW(), NOW()),
	(204, 'Svalbard i Jan Mayen', 'SJ', NOW(), NOW()),
	(205, 'Suazi', 'SZ', NOW(), NOW()),
	(206, 'Szwecja', 'SE', NOW(), NOW()),
	(207, 'Szwajcaria', 'CH', NOW(), NOW()),
	(208, 'Syria', 'SY', NOW(), NOW()),
	(209, 'Tajwan', 'TW', NOW(), NOW()),
	(210, 'Tadżykistan', 'TJ', NOW(), NOW()),
	(211, 'Tanzania', 'TZ', NOW(), NOW()),
	(212, 'Tajlandia', 'TH', NOW(), NOW()),
	(213, 'Timor Wschodni', 'TL', NOW(), NOW()),
	(214, 'Togo', 'TG', NOW(), NOW()),
	(215, 'Tokelau', 'TK', NOW(), NOW()),
	(216, 'Tonga', 'TO', NOW(), NOW()),
	(217, 'Trinidad i Tobago', 'TT', NOW(), NOW()),
	(218, 'Tunezja', 'TN', NOW(), NOW()),
	(219, 'Turcja', 'TR', NOW(), NOW()),
	(220, 'Turkmenistan', 'TM', NOW(), NOW()),
	(221, 'Wyspy Turks i Caicos', 'TC', NOW(), NOW()),
	(222, 'Tuvalu', 'TV', NOW(), NOW()),
	(223, 'Uganda', 'UG', NOW(), NOW()),
	(224, 'Ukraina', 'UA', NOW(), NOW()),
	(225, 'Zjednoczone Emiraty Arabskie', 'AE', NOW(), NOW()),
	(226, 'Wielka Brytania', 'GB', NOW(), NOW()),
	(227, 'Stany Zjednoczone', 'US', NOW(), NOW()),
	(228, 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych', 'UM', NOW(), NOW()),
	(229, 'Urugwaj', 'UY', NOW(), NOW()),
	(230, 'Uzbekistan', 'UZ', NOW(), NOW()),
	(231, 'Vanuatu', 'VU', NOW(), NOW()),
	(232, 'Wenezuela', 'VE', NOW(), NOW()),
	(233, 'Wietnam', 'VN', NOW(), NOW()),
	(234, 'Brytyjskie Wyspy Dziewicze', 'VG', NOW(), NOW()),
	(235, 'Wyspy Dziewicze Stanów Zjednoczonych', 'VI', NOW(), NOW()),
	(236, 'Wallis i Futuna', 'WF', NOW(), NOW()),
	(237, 'Sahara Zachodnia', 'EH', NOW(), NOW()),
	(238, 'Jemen', 'YE', NOW(), NOW()),
	(239, 'Zambia', 'ZM', NOW(), NOW()),
	(240, 'Zimbabwe', 'ZW', NOW(), NOW());
