INSERT INTO `dict_provinces` (`id`, `dict_country_id`, `province`, `created_at`, `updated_at`) VALUES
	(1, 171, 'dolnośląskie', NOW(), NOW()),
	(2, 171, 'kujawsko-pomorskie', NOW(), NOW()),
	(3, 171, 'lubelskie', NOW(), NOW()),
	(4, 171, 'lubuskie', NOW(), NOW()),
	(5, 171, 'łódzkie', NOW(), NOW()),
	(6, 171, 'małopolskie', NOW(), NOW()),
	(7, 171, 'mazowieckie', NOW(), NOW()),
	(8, 171, 'opolskie', NOW(), NOW()),
	(9, 171, 'podkarpackie', NOW(), NOW()),
	(10, 171, 'podlaskie', NOW(), NOW()),
	(11, 171, 'pomorskie', NOW(), NOW()),
	(12, 171, 'śląskie', NOW(), NOW()),
	(13, 171, 'świętokrzyskie', NOW(), NOW()),
	(14, 171, 'warmińsko-mazurskie', NOW(), NOW()),
	(15, 171, 'wielkopolskie', NOW(), NOW()),
	(16, 171, 'zachodniopomorskie', NOW(), NOW());
